##### GomaGateway
version: "1.0"
gateway:
  sslCertFile: cert.pem
  sslKeyFile: key.pem
  writeTimeout: 15
  readTimeout: 15
  idleTimeout: 30
  disableRouteHealthCheckError: false
  disableHealthCheckStatus: false
  enableMetrics: true
  disableKeepAlive: false
  ##### Define routes
  routes:
    - name: nextcloud
      hosts:
      - nextcloud.example.dev
      - nextcloud.localhost
      path: /
      rewrite: /
      destination: http://nextcloud
      disableHostFording: false
      blockCommonExploits: false
      insecureSkipVerify: false
      rateLimit: 0
      healthCheck:
        path: /
        interval: 15s
        timeout: 10s
        healthyStatuses:
          - 200
          - 404
      cors:
        origins:
          - https://nextcloud.example.dev
          - http://nextcloud.example.dev
          - http://nextcloud.localhost
        headers:

      interceptErrors: []
      middlewares: []
    - name: wordpress
      hosts:
      - wordpress.example.dev
      - wordpress.localhost
      path: /
      rewrite: /
      ## Example of load balancing route
      backends:
       - http://wordpress
       - http://wordpress
      disableHostFording: false
      blockCommonExploits: false
      rateLimit: 0
      healthCheck:
        path: /
        interval: 15s
        timeout: 10s
        healthyStatuses:
          - 200
          - 404
      cors:
        origins:
          - https://wordpress.example.dev
          - http://wordpress.example.dev
          - http://wordpress.localhost
      interceptErrors: []
      middlewares: []
middlewares:
  - name: basic-auth
    type: basic
    paths:
      - /admin/*
    rule:
      username: admin
      password: admin