##### GomaGateway
version: 2
gateway:
  writeTimeout: 15
  readTimeout: 15
  idleTimeout: 30
  tls:  # Global TLS configuration for the gateway
    keys:  # List of TLS certificates and private keys
     # - cert: /path/to/certificate.crt  # File path to the TLS certificate
     #   key: /path/to/private.key  # File path to the private key
  ##### Define routes
  routes:
    - path: /
      name: nextcloud
      disabled: false
      hosts:
      - nextcloud.example.dev
      - nextcloud.localhost
      rewrite: /
      destination: http://nextcloud
      blockCommonExploits: false
      insecureSkipVerify: false
      healthCheck:
        path: /
        interval: 15s
        timeout: 10s
        healthyStatuses:
          - 200
          - 404
      cors:
        origins:
          - https://nextcloud.example.dev
          - http://nextcloud.example.dev
          - http://nextcloud.localhost
        headers:
      middlewares: []
    - name: wordpress
      disabled: false
      hosts:
      - wordpress.example.dev
      - wordpress.localhost
      path: /
      rewrite: /
      ## Example of load balancing route
      backends:
       - endpoint: http://wordpress
         weight: 1
       - endpoint: http://wordpress2
         weight: 3
      blockCommonExploits: false
      healthCheck:
        path: /
        interval: 15s
        timeout: 10s
        healthyStatuses:
          - 200
          - 404
      cors:
        origins:
          - https://wordpress.example.dev
          - http://wordpress.example.dev
          - http://wordpress.localhost
      middlewares:
       #- basic-auth # Protech /wp-admin with second security basic auth
middlewares:
  - name: basic-auth
    type: basic
    paths:
      - /wp-admin
    rule:
      users: 
      - admin:admin
